#ifndef __DEFINES_H__
#define __DEFINES_H__
#define SETBIT(WORD,BITPOS) WORD|=(1<<BITPOS)
#define SSETBIT(WORD,BITPOS) WORD=(1<<BITPOS)
#define CLRBIT(WORD,BITPOS) WORD&=(~(1<<BITPOS))
#define SCLRBIT SSETBIT
#define CPLBIT(WORD,BITPOS) WORD^=(1<<BITPOS)
#define READBIT(WORD,BITPOS) ((WORD>>BITPOS)&1)
#define READNIBBLE(WORD,SBITPOS) ((WORD>>SBITPOS)&15)
#define WRITEBIT(WORD,BITPOS,BIT) WORD=(WORD&(~(1<<BITPOS)))|(BIT<<BITPOS)
#define WRITEPAIRBIT(WORD,BITPAIRPOS,PAIRBIT) WORD=(WORD&(~(3<<BITPAIRPOS)))|\
(PAIRBIT<<BITPAIRPOS)
#define WRITENIBBLE(WORD,SBITPOS,NIBBLE) WORD=(WORD&(~(15<<SBITPOS)))|\
(NIBBLE<<SBITPOS)
#define WRITEBYTE(WORD,SBITPOS,BYTE) WORD=(WORD&(~(255<<SBITPOS)))|(BYTE<<SBITPOS)
#endif
